### ISSUE TITLE
Fail to start

### ISSUE THREAD

**Issue by vds** [boltdb/boltd#7]
Using tip of both boltdb and boltd, when trying to get boltd I get:
$ go get github.com/boltdb/boltd/...
# github.com/boltdb/boltd/cmd/boltd
src/github.com/boltdb/boltd/cmd/boltd/main.go:27: not enough arguments in call to bolt.Open

**Comment by joyrexus** [comment]
@vds @benbjohnson Is this resolved with #4 and #9 merged?  If so, close the issue.

**Comment by benbjohnson** [comment]
Yes. Closing.

**Comment by vds** [comment]
WFM
